# Twitcaspy
# Copyright 2021 Alma-field
# See LICENSE for details.
#
# based on tweepy(https://github.com/tweepy/tweepy)
# Copyright (c) 2009-2021 Joshua Roesslein

name: Deploy

on:
    release:
        types: [published]

jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
          - uses: actions/checkout@v2
          - name: Setup Python
            uses: actions/setup-python@v2
            with:
                python-version: '3.x'
          - name: Install dependencies
            run: |
                python -m pip install --upgrade pip
                pip install twine wheel
          - name: Build and publish
            env:
                TWINE_USERNAME: __token__
                TWINE_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
            run: |
                python setup.py sdist
                twine upload dist/*
